---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: macos-10.12
  - name: windows-10
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.7

suites:
  - name: default
    run_list:
      - recipe[visual_studio_code]
  - name: direct
    run_list:
      - recipe[visual_studio_code]
    attributes:
      visual_studio_code:
        app:
          source: direct
